/**
 * GET /og?season=YYYY&seriesId=...&lang=en|ja
 *
 * Returns the per-series OpenGraph image as an `image/svg+xml` document,
 * generated by the shared pure {@link buildOgImageSvg}. The image is cached
 * in DynamoDB keyed by seriesId + series situation (high.wins-low.wins) + lang
 * (see {@link ogCacheKey}): a cache hit returns the stored SVG WITHOUT
 * rebuilding; a miss builds it, stores it, and returns it.
 *
 * Contract:
 *   - A missing/blank `seriesId` returns HTTP 400 (JSON).
 *   - An unknown series (not resolvable in the bracket) returns HTTP 404 (JSON)
 *     rather than a placeholder image, so a bad link is an honest error.
 *   - On success, HTTP 200 with `Content-Type: image/svg+xml` and a
 *     `Cache-Control` header (see {@link rawResponse} / SHARE_CACHE_CONTROL).
 *
 * This handler never calls Bedrock; it only reads/writes DynamoDB and the
 * public MLB API via the shared BracketService (cache-first + seed fallback).
 */
import type { APIGatewayProxyHandlerV2 } from 'aws-lambda';
import { buildOgImageSvg, DEFAULT_NARRATIVE_LANGUAGE } from '@mlb/shared';
import { BracketService } from '../service/bracketService.js';
import { ogCacheKey } from '../service/ogCacheKey.js';
import { DynamoBracketStore, type BracketStore } from '../store/dynamo.js';
import { jsonResponse, parseLanguage, parseSeason, parseSeriesId, rawResponse } from './http.js';

const SVG_CONTENT_TYPE = 'image/svg+xml';

const service = new BracketService();
const store: BracketStore = new DynamoBracketStore();

export const handler: APIGatewayProxyHandlerV2 = async (event) => {
  const seriesId = parseSeriesId(event.queryStringParameters?.seriesId);
  if (seriesId === undefined) {
    return jsonResponse(400, { message: 'seriesId is required.' });
  }

  const season = parseSeason(event.queryStringParameters?.season);
  if (season === undefined) {
    return jsonResponse(400, { message: 'Invalid season; expected a 4-digit year.' });
  }

  // Lenient optional language: a missing/unknown value falls back to the
  // shared default rather than 400 (mirrors the prediction handler).
  const lang = parseLanguage(event.queryStringParameters?.lang) ?? DEFAULT_NARRATIVE_LANGUAGE;

  try {
    const resolved = await service.getSeriesWithBracket(seriesId, season);
    if (!resolved) {
      return jsonResponse(404, { message: `Series not found: ${seriesId}` });
    }

    const { series } = resolved;
    const cacheKey = ogCacheKey({
      seriesId,
      highWins: series.high.wins,
      lowWins: series.low.wins,
      lang,
    });

    // Cache hit: return the stored SVG WITHOUT rebuilding it.
    const cached = await store.getCachedOgImage(cacheKey);
    if (cached) {
      return rawResponse(200, cached, SVG_CONTENT_TYPE);
    }

    // Cache miss: build via the shared pure builder, store, and return.
    const svg = buildOgImageSvg({ series, season, lang });
    await store.putCachedOgImage(cacheKey, svg);
    return rawResponse(200, svg, SVG_CONTENT_TYPE);
  } catch {
    return jsonResponse(500, { message: 'Failed to build the OG image.' });
  }
};
