/**
 * Shared HTTP helpers for the API Gateway (HTTP API) Lambda handlers:
 * CORS-enabled JSON responses and a season query parser.
 */
import type { APIGatewayProxyStructuredResultV2 } from 'aws-lambda';
import { CURRENT_YEAR, type NarrativeLanguage } from '@mlb/shared';

export const CORS_HEADERS: Record<string, string> = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
  'Content-Type': 'application/json',
};

/** Builds a CORS-enabled JSON response. */
export function jsonResponse(
  statusCode: number,
  body: unknown,
): APIGatewayProxyStructuredResultV2 {
  return {
    statusCode,
    headers: CORS_HEADERS,
    body: JSON.stringify(body),
  };
}

/**
 * Default `Cache-Control` for the share/OG responses: cacheable for 15 minutes
 * (matching the DynamoDB OG-image/share TTL) so CloudFront and crawler caches
 * can serve the generated bytes without hammering the Lambda.
 */
export const SHARE_CACHE_CONTROL = 'public, max-age=900';

/**
 * Builds a non-JSON (SVG/HTML) response for the share/OG endpoints. Sets the
 * given `Content-Type`, a permissive CORS `Access-Control-Allow-Origin` (`*`,
 * matching {@link CORS_HEADERS}), and a `Cache-Control` header. Extra headers
 * can be merged in and override the defaults.
 */
export function rawResponse(
  statusCode: number,
  body: string,
  contentType: string,
  extraHeaders?: Record<string, string>,
): APIGatewayProxyStructuredResultV2 {
  return {
    statusCode,
    headers: {
      'Content-Type': contentType,
      'Access-Control-Allow-Origin': '*',
      'Cache-Control': SHARE_CACHE_CONTROL,
      ...extraHeaders,
    },
    body,
  };
}

/**
 * Parses a `seriesId` from a query string value. Returns the trimmed non-empty
 * string, or `undefined` when the value is missing/blank (the handler rejects
 * `undefined` with a 400). The id shape is validated downstream when the series
 * is resolved from the bracket.
 */
export function parseSeriesId(value: string | undefined): string | undefined {
  if (value === undefined || value === null) return undefined;
  const trimmed = value.trim();
  return trimmed === '' ? undefined : trimmed;
}

/**
 * Default season when none is supplied by the caller. Derived from the shared
 * {@link CURRENT_YEAR} so the app's notion of "now" lives in one place rather
 * than being a scattered literal.
 */
export const DEFAULT_SEASON = CURRENT_YEAR;

/**
 * Parses a season from a query string value. Returns a valid 4-digit year or
 * `undefined` when the input is malformed.
 */
export function parseSeason(value: string | undefined): number | undefined {
  if (value === undefined) return DEFAULT_SEASON;
  if (!/^\d{4}$/.test(value)) return undefined;
  const season = Number(value);
  return Number.isInteger(season) ? season : undefined;
}

/**
 * Parses a `gamePk` from a query string value. Returns a positive integer or
 * `undefined` when the input is missing, non-numeric, or not a positive integer
 * (the handler rejects `undefined` with a 400).
 */
export function parseGamePk(value: string | undefined): number | undefined {
  if (value === undefined || value === null || value.trim() === '') return undefined;
  if (!/^\d+$/.test(value.trim())) return undefined;
  const gamePk = Number(value);
  return Number.isInteger(gamePk) && gamePk > 0 ? gamePk : undefined;
}

/**
 * Parses the optional prediction `accuracy` control from a request value
 * (query string or JSON body, either a string or number). Returns `undefined`
 * for a missing value so the service/model default applies, and for any
 * non-numeric input (accuracy is a best-effort tuning knob, not a hard
 * validation gate like season). A valid number is returned as-is; the model
 * clamps it into its supported [0, 1] range.
 */
export function parseAccuracy(value: string | number | undefined): number | undefined {
  if (value === undefined || value === null) return undefined;
  const accuracy = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(accuracy) ? accuracy : undefined;
}

/**
 * Parses the optional narrative `language` control (query string or JSON body).
 * Returns `undefined` for a missing/unknown value so the service default
 * applies; it is a best-effort control, not a hard validation gate, so this
 * NEVER signals an error for an unknown language. Case is normalized and a
 * region subtag is tolerated ('en-US' -> 'en', 'ja-JP' -> 'ja'); only 'en' and
 * 'ja' are recognized, anything else yields `undefined`.
 */
export function parseLanguage(
  value: string | undefined,
): NarrativeLanguage | undefined {
  if (value === undefined || value === null) return undefined;
  const normalized = value.trim().toLowerCase().split('-')[0];
  if (normalized === 'en' || normalized === 'ja') {
    return normalized;
  }
  return undefined;
}

/**
 * Parses the optional `model` control (query string or JSON body). Returns the
 * raw non-empty string unchanged (the service allowlists it via
 * `resolveModelId`) or `undefined` for a missing/empty value so the service
 * default applies. Like {@link parseAccuracy}, this never signals an error for
 * an unknown model.
 */
export function parseModelId(value: string | undefined): string | undefined {
  if (value === undefined || value === null) return undefined;
  const trimmed = value.trim();
  return trimmed === '' ? undefined : trimmed;
}
